### ISSUE TITLE
Suggestion - Pause, delete commands, Spotify

### ISSUE THREAD

**Issue by andreagdipaolo** [kursadHD/TgMusicBot#1]
Hi, it would be nice if the userbot could (granted the permission) delete command messages to keep the groups clean.
Also, it would be nice to implement a pause and resume command.
Finally, it would be nice to be able to play spotify links also for single songs and not only playlists.

Thank you for your work.

**Comment by kursadHD** [comment]
I will add these features as soon as possible. Thank you for your suggestions.
